#!/usr/bin/env bash
# Idempotent Cloud Agent setup for App Manager (FastAPI backend + Vite/React frontend).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# --- System dependency: python venv module (needed to create .venv) ---
if ! python3 -c "import ensurepip" >/dev/null 2>&1; then
  sudo apt-get update -y
  sudo apt-get install -y python3.12-venv
fi

# --- Backend: virtualenv + Python dependencies ---
cd "$REPO_ROOT/backend"
if [ ! -x ".venv/bin/python" ]; then
  python3 -m venv .venv
fi
./.venv/bin/python -m pip install --upgrade pip
./.venv/bin/python -m pip install -r requirements.txt

# --- Backend: local dev .env (generated once; never committed) ---
if [ ! -f ".env" ]; then
  JWT_SECRET="$(./.venv/bin/python -c 'import secrets; print(secrets.token_hex(32))')"
  cat > .env <<EOF
# Local development environment (generated by .cursor/install.sh)
DEBUG=true
APP_URL=http://127.0.0.1:8000
FRONTEND_URL=http://localhost:5173
SHOPIFY_PUBLIC_URL=http://127.0.0.1:8000
SHOPIFY_ALLOW_DEV_TUNNEL=false
DATABASE_URL=sqlite:///./data/app_manager.db
JWT_SECRET_KEY=${JWT_SECRET}
ENCRYPTION_KEY=
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=
SMTP_USE_TLS=true
SHOPIFY_CLIENT_ID=
SHOPIFY_CLIENT_SECRET=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
OPENAI_API_KEY=
EOF
fi

# --- Frontend: npm dependencies ---
cd "$REPO_ROOT/frontend"
npm install

echo "App Manager setup complete."
